// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BgWrap: typeof import('./src/components/index/bgWrap/index.vue')['default']
    Character: typeof import('./src/components/cards/character/index.vue')['default']
    DialogEnterRoom: typeof import('./src/components/index/enterRoom/dialog-enter-room.vue')['default']
    DialogLogin: typeof import('./src/components/index/header/dialog-login.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EnterRoom: typeof import('./src/components/index/enterRoom/enter-room.vue')['default']
    Footer: typeof import('./src/components/index/footer/index.vue')['default']
    Header: typeof import('./src/components/index/header/index.vue')['default']
    OpponentPlayer: typeof import('./src/components/room/playerContent/opponent-player.vue')['default']
    OwnPlayer: typeof import('./src/components/room/playerContent/own-player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    TcgAvatar: typeof import('./src/components/custom/tcg-avatar/index.vue')['default']
    TcgDialog: typeof import('./src/components/custom/tcg-dialog/index.vue')['default']
    UserHeader: typeof import('./src/components/user/user-header.vue')['default']
    UserLogin: typeof import('./src/components/index/header/user-login.vue')['default']
    UserMenu: typeof import('./src/components/user/user-menu.vue')['default']
  }
}
